### PR TITLE
Enhance visuals

### PR DESCRIPTION
**Pull request by nikeee**
This PR changes the style to match some Windows 7 style guidelines and colors.

Screenshot

### CODE REVIEW

**Review by Saibamen — APPROVED** [review]

**Comment by nikeee** [comment]
Anything that prevents this from merging?

**Comment by nikeee** [comment]
I'm currently cleaning up my open PRs. I'm closing this PR soon.

**Comment by Saibamen** [comment]
Why?

**Comment by nikeee** [comment]
It's nothing personal. I just don't like having that many open PRs.

Also, this PR touches code that is generated by the windows forms designer. It may have no merge conflicts, but after almost a year of not being updated, it may also be outdated. As this PR contains rather trivial changes, it may be a better option to just do everything again.

**Pull request closed without merging**
